application: hardwave-tweeder
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /feed/.*
  script: main.app

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static

libraries:
- name: webapp2
  version: "2.5.2"
- name: django
  version: "1.4"
- name: lxml
  version: "latest"

inbound_services:
- warmup

